const User = require('../models/User')
const asyncHandler = require('express-async-handler');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

const generateToken = (id) => {
    return jwt.sign({ id }, process.env.JWT_SECRET || 'fallback-secret', { expiresIn: '30d' });
};


const getAllUsers = asyncHandler(async(req,res)=>{
    const users = await User.find().select('-password').lean()
    if(!users?.length){
        return res.status(400).json({message:"No users found"})
    }
    res.json(users)
})

// Get user by ID
const getUserById = asyncHandler(async (req, res) => {
  const user = await User.findById(req.params.id).select('-password');
  if (!user) {
    res.status(404);
    throw new Error('User not found');
  }
  res.json({ user });
});

// Login User
const loginUser = asyncHandler(async (req, res) => {
  const { email, password } = req.body;

  if (!email || !password) {
    res.status(400);
    throw new Error('Please add email and password');
  }

  const user = await User.findOne({ email });

  if (user && (await bcrypt.compare(password, user.password))) {
    res.json({
      _id: user._id,
      user_id: user.user_id, // Include user_id in response
      username: user.username,
      name: user.name,
      email: user.email,
      token: generateToken(user._id),
      business_profile: user.business_profile,
      subscription: user.subscription
    });
  } else {
    res.status(400);
    throw new Error('Invalid credentials');
  }
});


const createUser = asyncHandler(async (req, res) => {
  const { username, email, password, name, business_type, marketing_goal, target_audience } = req.body;

  if (!username || !email || !password || !name) {
      res.status(400);
      throw new Error('Please add all required fields: username, email, password, name');
  }

  const userExists = await User.findOne({ $or: [{ email }, { username }] });
  if (userExists) {
      res.status(400);
      throw new Error('User already exists with this email or username');
  }

  const salt = await bcrypt.genSalt(10);
  const hashedPassword = await bcrypt.hash(password, salt);

  // user_id will be automatically generated by the schema
  const user = await User.create({
      username,
      email,
      password: hashedPassword,
      name,
      business_profile: {
          industry: business_type || 'other',
          target_audience: target_audience || [],
          marketing_goals: marketing_goal ? [marketing_goal] : ['brand_awareness']
      }
  });

  if (user) {
      const token = generateToken(user._id);
      res.status(201).json({
          _id: user._id,
          user_id: user.user_id, // Include the auto-generated user_id
          username: user.username,
          name: user.name,
          email: user.email,
          token,
          business_profile: user.business_profile,
          subscription: user.subscription,
          usage_metrics: user.usage_metrics
      });
  } else {
      res.status(400);
      throw new Error('Invalid user data');
  }
});

// Update User
const updateUser = asyncHandler(async (req, res) => {
  const updates = req.body;
  
  // Remove sensitive fields
  delete updates.password;
  delete updates._id;
  delete updates.user_id; // Prevent user_id from being changed

  const updatedUser = await User.findByIdAndUpdate(
    req.params.id,
    { $set: updates },
    { new: true, runValidators: true }
  ).select('-password');

  if (!updatedUser) {
    res.status(404);
    throw new Error('User not found');
  }

  res.json({
    message: 'User updated successfully',
    user: updatedUser
  });
});

// Delete User
const deleteUser = asyncHandler(async(req,res)=>{
    const user = await User.findById(req.params.id);
    if (!user) {
        res.status(404);
        throw new Error('User not found');
    }

    await User.findByIdAndDelete(req.params.id);
    res.json({ message: 'User deleted successfully' });
});

module.exports = {
    getAllUsers,
    getUserById,
    createUser,
    loginUser,
    updateUser,
    deleteUser
}